title: rapidpulse.dev
description: Test Site

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
